on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Run actions test
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run action
        id: action
        uses: ./
        with:
          username: asperan
      - name: test the email is correct and git is configured
        run: >
          test "${{ steps.action.outputs.email }}" == "alex.speranza@studio.unibo.it" &&
          test "$(git config --global user.name)" == "asperan" &&
          test "$(git config --global user.email)" == "alex.speranza@studio.unibo.it"

